version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y yarn
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker info
      - yarn install
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=265935852574.dkr.ecr.us-east-2.amazonaws.com/endmisconductdockers
      - AWS_ACCOUNT=265935852574.dkr.ecr.us-east-2.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - yarn build
      - export MOBILE_SERVER_NAME=EC2Co-EcsEl-1B9URBXI5GY8A-620161936.us-east-2.elb.amazonaws.com 
      - sed -e "s/{{MOBILE_SERVER_NAME}}/$MOBILE_SERVER_NAME/" nginx.conf.template > nginx.conf
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - rm nginx.conf
      - ContainerName="cpdbfrontend"
      - ImageURI=$REPOSITORY_URI:latest
      - printf '[{"name":"CONTAINER_NAME","imageUri":"IMAGE_URI"}]' > imagedefinitions.json
      - sed -i -e "s|CONTAINER_NAME|$ContainerName|g" imagedefinitions.json
      - sed -i -e "s|IMAGE_URI|$ImageURI|g" imagedefinitions.json
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
        - imagedefinitions.json
